service: elm-todo-app
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
functions:
  getTodos:
    handler: handler.getTodos

    events:
      - http:
          path: todos
          method: get
          integration: lambda
          cors: true
          resp: json
  postTodo:
    handler: handler.postTodo
    events:
      - http:
          path: todos
          method: post
          integration: lambda
          resp: json
          cors: true
  patchTodo:
    handler: handler.patchTodo
    events:
      - http:
          path: todos/{id}
          method: patch
          integration: lambda
          resp: json
          cors: true
resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: elmTodo
